# Generated by Django 2.2.5 on 2019-09-07 18:52

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('rated', models.CharField(max_length=25)),
                ('runtime', models.IntegerField()),
                ('genre', models.TextField()),
                ('director', models.TextField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('awards', models.TextField()),
                ('poster', models.TextField()),
                ('ratings', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), size=None)),
                ('metascore', models.IntegerField()),
                ('imdbrating', models.IntegerField()),
                ('imdbvotes', models.IntegerField()),
                ('imdbid', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('dvd', models.CharField(max_length=25)),
                ('boxoffice', models.CharField(max_length=60)),
                ('production', models.CharField(max_length=60)),
                ('website', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
