# Generated by Django 2.2.5 on 2019-09-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbrating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=25),
        ),
    ]
