# Generated by Django 2.2.5 on 2019-09-08 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190908_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.date(2019, 9, 8)),
            preserve_default=False,
        ),
    ]
